service:
  name: service-frontend-proxy
image:
  repository: 952893849914.dkr.ecr.us-east-1.amazonaws.com/aicares-application/frontend-proxy
containerPort: 8080
serviceType: LoadBalancer
resources:
  limits:
    memory: "65Mi"
  requests:
    memory: "32Mi"
    cpu: "50m"
env:
  - name: FRONTEND_HOST
    value: "frontend"
  - name: FRONTEND_PORT
    value: "8080"
  - name: TELEMETRY_DOCS_HOST
    value: "telemetry-docs"
  - name: TELEMETRY_DOCS_PORT
    value: "8000"
nodeSelector:
  eks.amazonaws.com/nodegroup: graviton-workers
